version: '3.7'

services:  
  
  main:
    container_name: imdb-api
    restart: always
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 5678:5678
      - 9229:9229
    command: npm run start
    env_file:
      - .env