name: Push main
on:
  push:
    branches:
      - main
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
        
    - name: Install dependencies
      run: npm ci

    - name: Run all tests
      run: npm test